const initialPowerBanks = [
    { id: 'PB-001', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-002', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-003', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-004', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-005', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-006', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-007', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-008', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-009', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-010', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-011', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-012', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-013', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-014', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-015', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-016', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-017', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-018', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-019', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-020', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-021', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-022', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-023', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-024', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-025', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-026', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-027', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-028', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-029', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-030', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-031', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-032', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-033', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-034', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-035', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-036', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-037', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-038', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-039', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-040', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-041', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-042', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-043', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-044', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-045', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-046', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-047', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-048', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-049', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-050', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-051', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-052', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-053', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-054', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-055', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-056', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-057', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-058', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-059', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-060', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-061', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-062', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-063', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-064', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-065', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-066', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-067', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-068', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-069', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-070', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-071', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-072', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-073', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-074', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-075', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-076', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-077', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-078', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-079', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-080', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-081', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-082', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-083', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-084', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-085', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-086', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-087', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-088', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-089', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-090', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-091', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-092', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-093', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-094', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-095', status: 'AVAILABLE', condition: 'GOOD' },
    { id: 'PB-096', status: 'AVAILABLE', condition: 'GOOD' }
];

const initialRentals = [];

const initializeData = () => {
    const { Storage } = window.JudetexUtils;

    if (!Storage.get('powerbanks')) {
        Storage.set('powerbanks', initialPowerBanks);
    }

    if (!Storage.get('rentals')) {
        Storage.set('rentals', initialRentals);
    }
};

initializeData();
